version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: atk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: atk
      MYSQL_USER: atkuser
      MYSQL_PASSWORD: atkpass
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: